version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sustainability-network
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-sustainability}

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4001}:${PORT:-4001}"
    depends_on:
      - mongodb
    environment:
      - PORT=${PORT:-4001}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/sustainability}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=${NODE_ENV:-development}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:4000}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - sustainability-network

networks:
  sustainability-network:
    driver: bridge

volumes:
  mongodb_data:
